name: Github release trigger

on:
  release:
    types: [published]
jobs:
  publish-to-npmjs:
    uses: ./.github/workflows/publish-to-npmjs.yml
    with:
      prerelease: ${{ github.event.release.prerelease }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
