name: Manual pre-release publish to NPM

on: workflow_dispatch

jobs:
  publish-to-npmjs:
    uses: ./.github/workflows/publish-to-npmjs.yml
    with:
      prerelease: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
